### ISSUE TITLE
Update endpoint

### ISSUE THREAD

**Issue by mholt** [aarongable/draft-acme-ari#55]
I'm updating [acmez](https://github.com/mholt/acmez) to conform with the [latest spec draft 3](https://www.ietf.org/archive/id/draft-ietf-acme-ari-03.html), and realized I didn't know how to update my `UpdateRenewalInfo()` function.

I might have missed the reasons for the edits, but I noticed drafts 2 and 3 don't have a section 4.2 about updating renewal status anymore. Just wanted to ask about that.

The language in section 4.1 still says:

> This new resource both allows clients to query the server for suggestions on when they should renew certificates, and allows clients to inform the server when they have completed renewal (or otherwise replaced the certificate to their satisfaction).

PS. I like the changes to the renewal endpoint URI, much simpler!! I was able to delete about 100 lines of convoluted code.

**Comment by aarongable** [comment]
That's correct, the ability to POST to the renewalInfo endpoint to mark a certificate as replaced has been (ahem) replaced by the ability to mark a new-order request as replacing a previous certificate. This reduces the total number of requests in an issuance flow, and gives CAs much more context about that replacement, at the cost of some flexibility (e.g. indicating that a cert has been replaced via issuance from a different CA).

Thanks for noting the vestigial language in 4.1, I'll fix that.

**Comment by mholt** [comment]
Ah, gotcha. Thank you for bridging the gap in my understanding.
