### ISSUE TITLE
Provide URL to replacing order on `alreadyReplaced` errors

### ISSUE THREAD

**Issue by felixfontein** [aarongable/draft-acme-ari#73]
It would be really helpful to client writers if a `alreadyReplaced` error would include the URL of the order that replaced the certificate.

I'm not sure how expensive that would be to implement. I checked out Pebble, there the conflict is detected by checking a flag of the original order that's replaced. Using the ID of the replacing order instead of a boolean flag would be a rather simple change. I also checked Boulder; there a function `ReplacementOrderExists` is called to determine whether there's a replacing order, which basically only returns a boolean. I checked out its implementation, it also has the ID of the replacement order available, so it would be easy (as in: no DB changes, as data is already readily available) to change to also return that one.

As for how to return it, providing it as a `Location` header or as a part of the error document is both fine for me, as long as it is specified how it is returned :)

**Comment by aarongable** [comment]
ACME problem documents do not have a precedent for containing additional machine-readable error information like this. While I find this idea interesting, I don't think this is the right place to blaze new trail in this direction.
